The set S originally contains numbers from 1 to n. But unfortunately, due to the data error, one of the numbers in the set got duplicated to another number in the set, which results in repetition of one number and loss of another number.

Given an array nums representing the data status of this set after the error. Your task is to firstly find the number occurs twice and then find the number that is missing. Return them in the form of an array.

Example 1:
```
Input: nums = [1,2,2,4]
Output: [2,3]
```
Note:
* The given array size will in the range [2, 10000].
* The given array's numbers won't have any order.


# Solution 1(python, 56ms, O(1) time, O(1) space)
```python
# mathmatic solution
class Solution(object):
    def findErrorNums(self, nums):
        """
        :type nums: List[int]
        :rtype: List[int]
        """
        # size in the range[2,10000]
        n = len(nums)
        expectedSum = (n+1) * n / 2
        realSum = sum(nums)
        uniSum = sum(set(nums))
        repeat = realSum - uniSum
        miss = expectedSum - uniSum
        return [repeat,miss]
```
# Solution 2(python, 539ms, O(n) time, O(1) space)
```python
class Solution(object):
    def findErrorNums(self, nums):
        """
        :type nums: List[int]
        :rtype: List[int]
        """
        # size in the range[2,10000]
        repeat = 0
        miss = 0
        # sort, amortized time is O(n)
        for i in range(len(nums)): 
            if nums[i] != i + 1:
                pivot = nums[i]
                nums[i] = 0
                while pivot != 0 and nums[pivot - 1] != pivot:
                    temp = nums[pivot - 1]
                    nums[pivot - 1] = pivot
                    pivot = temp
                if pivot != 0:
                    repeat = pivot
        for i in range(len(nums)):
            if nums[i] == 0:
                miss = i + 1
        if repeat == 0 and miss == 0:
            return []
        return [repeat,miss]
```

# Solution 3(python, 83ms, O(n) time, O(n) space)
```python
class Solution(object):
    def findErrorNums(self, nums):
        """
        :type nums: List[int]
        :rtype: List[int]
        """
        # size in the range[2,10000]
        repeat = 0
        miss = 0
        bucket = [0 for i in range(len(nums)+1)]
        for i in nums:
            bucket[i] += 1
        for i in range(len(bucket)):
            if bucket[i] == 2:
                repeat = i
            if bucket[i] == 0:
                miss = i
        
        if miss > 0:
            return [repeat,miss]
```
